# Generated by Django 3.2.4 on 2022-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='julius',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
