# Generated by Django 3.2.4 on 2022-04-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_post_julius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='julius',
        ),
    ]
