# Generated by Django 3.2.4 on 2022-04-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_remove_post_julius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_url',
        ),
    ]
