# Generated by Django 3.2.4 on 2022-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_remove_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(default=1, max_length=200000),
            preserve_default=False,
        ),
    ]
