# Generated by Django 3.2.4 on 2022-05-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_post_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='badge',
            new_name='blog_badge',
        ),
    ]
