# Generated by Django 3.2.4 on 2022-05-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_alter_post_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='badge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
