# Generated by Django 3.2.4 on 2022-05-30 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_rename_contact_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='firtname',
            new_name='firstname',
        ),
    ]
