# Generated by Django 3.2.4 on 2022-04-24 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20220424_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=20000),
            preserve_default=False,
        ),
    ]
