# Generated by Django 3.2.4 on 2022-05-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='badge',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
