# Generated by Django 3.2.4 on 2022-05-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0016_rename_badge_post_blog_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_badge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
