# Generated by Django 3.2.4 on 2022-05-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='badge',
        ),
    ]
