# Generated by Django 3.2.4 on 2022-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='badge',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
    ]
