# Generated by Django 3.2.4 on 2022-05-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_alter_post_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='badge',
            field=models.CharField(max_length=200),
        ),
    ]
