# Generated by Django 3.2.4 on 2022-05-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_alter_post_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firtname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('forms_need', models.CharField(max_length=200)),
                ('de_message', models.TextField()),
            ],
        ),
    ]
