# Generated by Django 3.2.4 on 2022-05-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0028_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
